
server:
  port: 8051

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sqxsss/spring-service-config
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}

#-e EUREKA_SERVER_ADDRESS=http://host.docker.internal:8050/eureka
# add to the command while docker run